name: Create CODEOWNERS

on:
  workflow_dispatch:

jobs:
  CODEOWNERS:
    runs-on: ubuntu-latest
    strategy:
        max-parallel: 1
        # SET MATRIX WITH repositories TO MIGRATE
        matrix: ${{ fromJson(needs.Get-Repositories-to-Migrate.outputs.repositories) }}

    steps:
      - uses: actions/checkout@v3

      - name: Set and Create CODEOWNERS
        run: |
          owner=$(jq -r '.owner' repositories.json) && echo $owner
          repo_names=${{ matrix.repositories }}
          project_names=$(echo "$repo_names" | sed 's/-.*//')
          sed "s/\$ProjectKey/$project_names/g" codeowners_template.txt > CODEOWNERS
          cat CODEOWNERS




