name: Create CODEOWNERS

on:
  workflow_dispatch:

jobs:

  Get-Repositories-To-Inject:
      runs-on: ubuntu-latest
      outputs:
        REPOSITORIES: ${{ steps.set-matrix.outputs.REPO }}
      steps:
        - name: Checkout to repository
          uses: actions/checkout@v3
       
        - name: Set matrix data
          id: set-matrix
          # STORE REPOSITORIES.JSON INTO REPOSITORIES VARIABLE
          run: echo "REPOSITORIES=$(jq -r '.repositories[].repo_name' repositories.json)" >> $GITHUB_OUTPUT

  CODEOWNERS:
    runs-on: ubuntu-latest
    needs: [Get-Repositories-To-Inject]
    strategy:
        max-parallel: 1
        # SET MATRIX WITH repositories TO MIGRATE
        matrix: 
            repositories: ${{needs.Get-Repositories-To-Inject.outputs.REPOSITORIES}}

    steps:
      - uses: actions/checkout@v3

      - name: Set and Create CODEOWNERS
        run: |
          owner=$(jq -r '.owner' repositories.json) && echo $owner
          repo_names=${{ matrix.repositories }}
          project_names=$(echo "$repo_names" | sed 's/-.*//')
          sed "s/\$ProjectKey/$project_names/g" codeowners_template.txt > CODEOWNERS
          cat CODEOWNERS




