name: Create CODEOWNERS

on:
  workflow_dispatch:

jobs:

  Get-Repositories-To-Inject:
      runs-on: ubuntu-latest
      outputs:
        REPOSITORIES: ${{ steps.set-matrix.outputs.REPO }}
        OWNER: ${{ steps.set-owner.outputs.OW}}
      steps:
        - name: Checkout to repository
          uses: actions/checkout@v3
       
        - name: Set matrix data
          id: set-matrix
          run: echo "REPO=$(jq -c -r '.repositories | map(.repo_name)' < ./repositories.json)" >> $GITHUB_OUTPUT 

        - name: Set owner
          id: set-owner
          run: echo "OW=$(jq -r '.owner' repositories.json)" >> $GITHUB_OUTPUT 

  create-CODEOWNERS:
    runs-on: ubuntu-latest
    needs: [Get-Repositories-To-Inject]
    strategy:
        max-parallel: 1
        # SET MATRIX WITH repositories TO MIGRATE
        matrix: 
            repositories: ${{fromJson(needs.Get-Repositories-To-Inject.outputs.REPOSITORIES)}}

    steps:
      - uses: actions/checkout@v3

      - name: Set and Create CODEOWNERS
        run: |
          owner=$(jq -r '.owner' repositories.json) && echo $owner
          repo_names=${{ matrix.repositories }}
          project_names=$(echo "$repo_names" | sed 's/-.*//')
          sed "s/\$ProjectKey/$project_names/g" codeowners_template.txt > CODEOWNERS
          cat CODEOWNERS

      - name: Add File to Another Repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          OWNER: ${{ needs.Get-Repositories-To-Inject.outputs.OWNER }}
        run: |
          git clone https://${{ env.OWNER }}:${{ env.GH_TOKEN }}@github.com/${{ env.OWNER }}/${{ matrix.repositories }}.git
          ls
          git config --global user.email "jgonzalez-clever@cleveritgroup.com"
          git config --global user.name "jgonzalez"
          cd update-codeowners 
          mkdir .github
          ls
          cp -rf ../CODEOWNERS ./${{ matrix.repositories }}/.github/CODEOWNERS
          tree
          git add .
          git commit -m "Add file from GitHub Actions"
          git push origin main  



