name: Add File to Another Repo

on:
    workflow_dispatch:

jobs:
  add-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Add File to Another Repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git clone git clone https://jgonzalez-clever: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@github.com/jgonzalez-clever/update_codeowners.git
          cp ./codeowners_template.txt other-repo/./github/codeowners_template.txt
          cd other-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Add file from GitHub Actions"
          git push origin main  
