name: Add File to Another Repo

on:
    workflow_dispatch:

jobs:
  add-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Add File to Another Repo
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          REPO_URL="https://jgonzalez-clever:${{ env.GH_TOKEN }}@github.com/jgonzalez-clever/update_codeowners.git"  # reemplaza con la URL de tu otro repositorio
          git clone https://jgonzalez-clever:${{ env.GH_TOKEN }}@github.com/jgonzalez-clever/update_codeowners.git
          ls -h
          cd .. && ls -h
          cp ./codeowners_template.txt other-repo/./github/codeowners_template.txt
          cd other-repo
          git add .
          git commit -m "Add file from GitHub Actions"
          git push origin main  
