name: Mi Flujo

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3

      - id: step1
        run: |
            REPO_NAMES=$(jq -c -r '.repositories | map(.repo_name)' < ./repositories.json)
            echo "name=$REPO_NAMES" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "::set-output name=test::world"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job1.outputs.output2 }}
        run: echo "$OUTPUT1 $OUTPUT2"

  job3:
    runs-on: ubuntu-latest
    needs: job1
    strategy:
      matrix:
        repositories: ${{fromJson(needs.job1.outputs.output1)}}
    steps:
      - env:
          REPOSITORY: ${{ matrix.repositories }}
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job1.outputs.output2 }}
        run: echo "$REPOSITORY $OUTPUT1 $OUTPUT2"
