name: Mi Flujo

on:
    workflow_dispatch:

jobs:
    job1:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        output1: ${{ steps.step1.outputs.test }}
        output2: ${{ steps.step2.outputs.test }}
      steps:
        - id: step1
          run: echo "test=["PROJECTLEGENDS-repo1", "PROJECTMINERAL-repo2"]" >> "$GITHUB_OUTPUT"
        - id: step2
          run: | 
            matrix='{
            "platform": [
              "neon-captest-new",
              "neon-captest-reuse",
              "neonvm-captest-new"
            ]}'

    job3:
      runs-on: ubuntu-latest
      needs: job1
      strategy:
        max-parallel: 1
        # SET MATRIX WITH repositories TO MIGRATE
        matrix: 
            repositories: ${{fromJson(needs.job1.outputs.output2)}}
      steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"