name: Add File to Another Repo

on:
  push:
    branches:
      - main  # ajusta según sea necesario

jobs:
  add-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2

      - name: Add File to Another Repo
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          REPO_URL="hhttps://github.com/jgonzalez-clever/update_codeowners"  # reemplaza con la URL de tu otro repositorio
          git clone $REPO_URL other-repo
          cp ./codeowners_template.txt ./github/codeowners_template.txt
          cd other-repo
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add .
          git commit -m "Add file from GitHub Actions"
          git push origin main  
