name: BitBucket Server Migration Tool
on:
  workflow_dispatch:
  
jobs:
#  CSV-Generator:
#    runs-on: [ 'self-hosted' , 'macOS' , 'X64' ]
#    steps:
#      - name: Creacion de CSV
#        run: |
#          # GENERATE CSV OUTPUTS
#          echo mig_start_time,mig_end_time,migration_time\(secs\),repository_size\(bytes\),bbs_project,bbs_repo,gh_org,gh_repo,bbs_num_files,gh_num_files,bbs_num_prs,gh_num_prs,bbs_num_branches,gh_num_branches,status > CSV_PROJECTS_ANALYSIS.csv
  
  Get-Repositories-to-Migrate:
    runs-on: ubuntu-latest

    # CONFIGURE PROJECT MATRIX
    outputs:
      # SET PROJECTS OUTPUT FROM SET-MATRIX STEP
      PROJECTS: ${{ steps.set-matrix.outputs.PROJECTS }}
    
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v3
     
      - name: Set matrix data
        id: set-matrix
        # STORE PROJECTS.JSON INTO PROJECTS VARIABLE
        run: echo "PROJECTS=$(jq -c . < ./projects.json)" >> $GITHUB_OUTPUT
        
  Migration:
    runs-on: ubuntu-latest
    needs: Get-Repositories-to-Migrate
    strategy:
      max-parallel: 1
      # SET MATRIX WITH PROJECTS TO MIGRATE
      matrix: ${{ fromJson(needs.Get-Repositories-to-Migrate.outputs.PROJECTS) }}
      
    steps:
      - name: Creacion de CSV
        run: |
          # GENERATE CSV OUTPUTS
          echo mig_start_time,mig_end_time,migration_time\(secs\),repository_size\(bytes\),bbs_project,bbs_repo,gh_org,gh_repo,bbs_num_files,gh_num_files,bbs_num_prs,gh_num_prs,bbs_num_branches,gh_num_branches,status > CSV_PROJECTS_ANALYSIS.csv
